### PR TITLE
Various other historical source code

### PR DESCRIPTION
**Pull request by biappi**
This is a collection of various source code of historical importance I know and cherish.

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
Good addition!  There could be an entire PDP-10 section.  What else do we have?  MUD, Zork, Emacs, Scheme...

**Comment by larsbrinkhoff** [comment]
How about this?

http://github.com/larsbrinkhoff/emacs-history

**Comment by mscottford** [comment]
These are great additions. Thanks!

**Comment by mscottford** [comment]
@larsbrinkhoff Nice find with emasculated-history. Please add it in another pull request.

**Comment by mscottford** [comment]
Grr... auto correct fail. That’ll teach me fortrying to use my phone to comment on issues in the car. :( (Not driving, I promise)

**Comment by larsbrinkhoff** [comment]
You can edit issue comments, you know. :-)

**Pull request merged**
